CXX = g++
CXXFLAGS = -Wall -std=c++11
TARGET = jogo

OBJECTS = tabuleiro.o jogador.o cadastro.o lig4.o reversi.o main.o

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

tabuleiro.o: tabuleiro.cpp tabuleiro.hpp
	$(CXX) $(CXXFLAGS) -c tabuleiro.cpp

jogador.o: jogador.cpp jogador.hpp
	$(CXX) $(CXXFLAGS) -c jogador.cpp

cadastro.o: cadastro.cpp cadastro.hpp jogador.hpp
	$(CXX) $(CXXFLAGS) -c cadastro.cpp

lig4.o: lig4.cpp lig4.hpp tabuleiro.hpp
	$(CXX) $(CXXFLAGS) -c lig4.cpp

reversi.o: reversi.cpp reversi.hpp tabuleiro.hpp
	$(CXX) $(CXXFLAGS) -c reversi.cpp

main.o: main.cpp cadastro.hpp lig4.hpp reversi.hpp
	$(CXX) $(CXXFLAGS) -c main.cpp

clean:
	del /q $(OBJECTS) $(TARGET)